services:
  mysql:
    image: mysql:9.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ABab!!126098
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_USER=alstkdwh24
      - MYSQL_PASSWORD=ABab!!126098
      - MYSQL_DATABASE=joGpt
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  postgres:
    image: postgres:18.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ABab!!126098
      - POSTGRES_USER=alstkdwh24
      - POSTGRES_DB=joGpt
